### ISSUE TITLE
[BUG] fatal error: 'IpReturnCodes.hpp' file not found

### ISSUE THREAD

**Issue by yurivict** [esa/pygmo2#58]
pygmo2-2.15.0-139-g15cf30d fails to build with pagmo2-2.15.0-102-gdecda188 and Ipopt-3.12.13:

```
/usr/local/include/pagmo/algorithms/ipopt.hpp:41:10: fatal error: 'IpReturnCodes.hpp' file not found
#include <IpReturnCodes.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

The file ```/usr/local/include/coin/IpReturnCodes.hpp``` is installed, but this directory apparently isn't searched.

OS: FreeBSD 12.2
clang-10

**Comment by bluescarni** [comment]
@yurivict I am positive that this change in pagmo

https://github.com/esa/pagmo2/pull/412/commits/8a6d80ec62e1dd4929082e4b9de3027c4e9665e5

should fix the issue. Would you have a chance to try to install pagmo & pygmo from the latest GIT head and test if this is really the case?

**Comment by yurivict** [comment]
I already fixed up the port for this, and will retest when the next version will come out.

Thank you for fixing this!

Yuri

**Comment by bluescarni** [comment]
Ok, cheers!
